---
- hosts: win
  vars:
  
        
    #################################################
    ################# MANAGMENT #####################
    
    site_temporal: 5     # site.id de ansible para su almacenamiento temporal
    device_type : "HP Proliant Gen 10"
    device_role: "Servidores Fisicos"
    url_nb: "http://192.168.1.203"
    token_nb: "4c121d2ed2103e10fd2f4d9532dcb8e040fd0fc9"

  
    ##################################################
    # DEVICE
    ####################################################
    #HOST
    hostname: "{{ ansible_hostname }}"
    dominio: "{{ ansible_windows_domain }}"
    arquitecture: "{{ansible_architecture}}"
    version: "{{ ansible_distribution }}" 
    plataforma: "{{ ansible_os_family }}" 

    #CPU
    cpu_processor_model: "{{ansible_processor[2]}}"
    cpu_count: "{{ansible_processor_count}}"
    cpu_cores: "{{ansible_processor_cores}}"
    cpu_logics: "{{ansible_processor_threads_per_core}}"

    #MEMORY
    ram_total: "{{ansible_memtotal_mb}}"

    ##################################################
    # NETWORKING
    ####################################################
    ipv4: "{{ ansible_interfaces[item]['ipv4']['address'] }}"
    mac: "{{ ansible_interfaces[item]['macaddress'] }}"
    interface: "{{ ansible_facts.interfaces[item]['connection_name'] }}"
    prefix: "{{ ansible_interfaces[item]['ipv4']['prefix'] }}"
    ###################################################

  gather_facts: yes
  

  roles:
  - netbox_devices
  - netbox_ipam
  - netbox_disk
  - netbox_vm_basic
